---
abstract: 'Utilities for serialization tasks'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-SerializeUtils
requires:
  Data::Dump: 0
  JSON: 0
  PHP::Serialization: 0
  YAML::Syck: 0
  perl: 5.010001
version: 0.03
